# name = "cf-worker-ws-dev" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
name = "cf-worker-vmess" # todo

#main = "test/worker/worker-connect-test.js"
# main = "src/worker-vless.js"
main = "src/worker-vmess-beta.js"
# main = "src/test.js"

compatibility_date = "2023-05-26"
compatibility_flags = ["nodejs_compat"]

[vars]
UUID = "5e8cc50483a485100c166eb0cbb1b2ae"
PROXYIP = "edgetunnel.anycast.eu.org"
